# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [10]:
# Create a 1-dimensional NumPy array using np.array()
one_dimention = np.array([1,2,3])
one_dimention.ndim

# Create a 2-dimensional NumPy array using np.array()

two_dimention = np.array([[1,2,3], [3,4,5]])
two_dimention.ndim

# Create a 3-dimensional Numpy array using np.array()

three_dimentio = np.array([
    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [9,10,11,12],
        [13,14,15,16]
    ]
])

three_dimentio.ndim


3

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [16]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(one_dimention.shape)
print(one_dimention.ndim)
print(one_dimention.dtype)
print(one_dimention.size)
print(type(one_dimention))


(3,)
1
int64
3
<class 'numpy.ndarray'>


In [17]:
# Attributes of 2-dimensional array
print(two_dimention.shape)
print(two_dimention.ndim)
print(two_dimention.dtype)
print(two_dimention.size)
print(type(two_dimention))

(2, 3)
2
int64
6
<class 'numpy.ndarray'>


In [18]:
# Attributes of 3-dimensional array
print(three_dimentio.shape)
print(three_dimentio.ndim)
print(three_dimentio.dtype)
print(three_dimentio.size)
print(type(three_dimentio))

(2, 2, 4)
3
int64
16
<class 'numpy.ndarray'>


In [22]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
pd.DataFrame({'One dimention':one_dimention})

One dimention
0              1
1              2
2              3

In [23]:
# Create an array of shape (10, 2) with only ones
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [27]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.seed(1)
np.random.randint(0,10, size=(7,2))

array([[5, 8],
       [9, 5],
       [0, 0],
       [1, 7],
       [6, 9],
       [2, 4],
       [5, 2]])

In [28]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random(size=(3,5))

array([[0.52454816, 0.44345289, 0.22957721, 0.53441391, 0.91396202],
       [0.45720481, 0.43069857, 0.93912779, 0.77838924, 0.71597052],
       [0.8027575 , 0.09280081, 0.51815255, 0.86502025, 0.82914691]])

In [30]:
# Set the random seed to 42

np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10, size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [33]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_numb = np.random.randint(1,10, size=(3,7))
print(random_numb)
# Find the unique numbers in the array you just created
np.unique(random_numb)

[[2 5 8 9 9 1 9]
 [7 9 8 1 8 8 3]
 [1 8 3 3 1 5 7]]


array([1, 2, 3, 5, 7, 8, 9])

In [34]:
# Find the 0'th index of the latest array you created
random_numb[0]

array([2, 5, 8, 9, 9, 1, 9])

In [43]:
# Get the first 2 rows of latest array you created
random_numb[0:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [49]:
# Get the first 2 values of the first 2 rows of the latest array
random_numb[:2, :2]

array([[2, 5],
       [7, 9]])

In [52]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array = np.random.randint(0,10, (3,5))
ones_array = np.ones((3,5))
ones_array, random_array

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[3, 3, 4, 6, 6],
        [3, 6, 2, 5, 1],
        [9, 8, 4, 5, 3]]))

In [57]:
# Add the two arrays together
new_array = np.add(random_array, ones_array)
new_array

array([[ 4.,  4.,  5.,  7.,  7.],
       [ 4.,  7.,  3.,  6.,  2.],
       [10.,  9.,  5.,  6.,  4.]])

In [58]:
# Create another array of ones of shape (5, 3)
a2_ones = np.ones((5,3))

In [59]:
# Try add the array of ones and the other most recent array together
np.add(ones_array,a2_ones)

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

I can utilize transposition operations, for instance:

arr2_transposed = arr2.T

Alternatively, I can employ the reshape method:

arr1_reshaped = arr1.reshape(3, 5, 1)

arr2_reshaped = arr2.reshape(1, 5, 3)

By transposing with .T, I can switch the dimensions of arr2. On the other hand, with reshape, I can explicitly specify the desired shape of the arrays, allowing for more flexibility in array manipulations.

In [66]:
np.add(random_array, a2_ones.T)

array([[ 4.,  4.,  5.,  7.,  7.],
       [ 4.,  7.,  3.,  6.,  2.],
       [10.,  9.,  5.,  6.,  4.]])

In [67]:
# Create another array of ones of shape (3, 5)
new_ones = np.ones((3,5))

In [68]:
# Subtract the new array of ones from the other most recent array
np.subtract(random_array, new_ones)

array([[2., 2., 3., 5., 5.],
       [2., 5., 1., 4., 0.],
       [8., 7., 3., 4., 2.]])

In [70]:
# Multiply the ones array with the latest array
np.multiply(random_array, new_ones)

array([[3., 3., 4., 6., 6.],
       [3., 6., 2., 5., 1.],
       [9., 8., 4., 5., 3.]])

In [71]:
# Take the latest array to the power of 2 using '**'
random_array ** 2

array([[ 9,  9, 16, 36, 36],
       [ 9, 36,  4, 25,  1],
       [81, 64, 16, 25,  9]])

In [72]:
# Do the same thing with np.square()
np.square(random_array)

array([[ 9,  9, 16, 36, 36],
       [ 9, 36,  4, 25,  1],
       [81, 64, 16, 25,  9]])

In [73]:
# Find the mean of the latest array using np.mean()
np.mean(random_array)

4.533333333333333

In [74]:
# Find the maximum of the latest array using np.max()
np.max(random_array)

9

In [75]:
# Find the minimum of the latest array using np.min()
np.min(random_array)

1

In [76]:
# Find the standard deviation of the latest array
np.std(random_array)

2.124983660067897

In [77]:
# Find the variance of the latest array
np.var(random_array)

4.515555555555555

In [78]:
# Reshape the latest array to (3, 5, 1)
np.reshape(random_array, (3,5,1))

array([[[3],
        [3],
        [4],
        [6],
        [6]],

       [[3],
        [6],
        [2],
        [5],
        [1]],

       [[9],
        [8],
        [4],
        [5],
        [3]]])

In [87]:
# Transpose the latest array
random_array.shape, random_array.T

((3, 5),
 array([[3, 3, 9],
        [3, 6, 8],
        [4, 2, 4],
        [6, 5, 5],
        [6, 1, 3]]))

What does the transpose do?

In [92]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.seed(1)
array_random_one = np.random.randint(0,10, (3,3))
array_random_two = np.random.randint(0,10, (3,2))
array_random_one,array_random_two

(array([[5, 8, 9],
        [5, 0, 0],
        [1, 7, 6]]),
 array([[9, 2],
        [4, 5],
        [2, 4]]))

In [91]:
# Perform a dot product on the two newest arrays you created
np.dot(array_random_one, array_random_two)

array([[95, 86],
       [45, 10],
       [49, 61]])

In [93]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
np.random.seed(1)
array_random_one = np.random.randint(0,10, (4,3))
array_random_two = np.random.randint(0,10, (4,3))
array_random_one,array_random_two

(array([[5, 8, 9],
        [5, 0, 0],
        [1, 7, 6],
        [9, 2, 4]]),
 array([[5, 2, 4],
        [2, 4, 7],
        [7, 9, 1],
        [7, 0, 6]]))

In [94]:
# Perform a dot product on the two newest arrays you created
np.dot(array_random_one, array_random_two)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [95]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(array_random_one, array_random_two.T)

array([[ 77, 105, 116,  89],
       [ 25,  10,  35,  35],
       [ 43,  72,  76,  43],
       [ 65,  54,  85,  87]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [98]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
np.random.seed(1)
array_random_one = np.random.randint(0,10, (4,3))
array_random_two = np.random.randint(0,10, (4,3))
array_random_one,array_random_two


(array([[5, 8, 9],
        [5, 0, 0],
        [1, 7, 6],
        [9, 2, 4]]),
 array([[5, 2, 4],
        [2, 4, 7],
        [7, 9, 1],
        [7, 0, 6]]))

In [99]:
# Compare the two arrays with '>'
array_random_one > array_random_two

array([[False,  True,  True],
       [ True, False, False],
       [False, False,  True],
       [ True,  True, False]])

What happens when you compare the arrays with `>`?

In [100]:
# Compare the two arrays with '>='
array_random_one >= array_random_two

array([[ True,  True,  True],
       [ True, False, False],
       [False, False,  True],
       [ True,  True, False]])

In [101]:
# Find which elements of the first array are greater than 7
array_random_one > 7

array([[False,  True,  True],
       [False, False, False],
       [False, False, False],
       [ True, False, False]])

In [102]:
# Which parts of each array are equal? (try using '==')
array_random_one == array_random_two

array([[ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [103]:
# Sort one of the arrays you just created in ascending order
np.sort(array_random_one)

array([[5, 8, 9],
       [0, 0, 5],
       [1, 6, 7],
       [2, 4, 9]])

In [118]:
# Sort the indexes of one of the arrays you just created
np.argsort(array_random_one), array_random_one

(array([[0, 1, 2],
        [1, 2, 0],
        [0, 2, 1],
        [1, 2, 0]]),
 array([[5, 8, 9],
        [5, 0, 0],
        [1, 7, 6],
        [9, 2, 4]]))

In [116]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array_random_two)

7

In [115]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array_random_two)

10

In [114]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array_random_one, axis=1), array_random_one

(array([2, 0, 1, 0]),
 array([[5, 8, 9],
        [5, 0, 0],
        [1, 7, 6],
        [9, 2, 4]]))

In [112]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(array_random_one, axis=0), array_random_one

(array([3, 0, 0]),
 array([[5, 8, 9],
        [5, 0, 0],
        [1, 7, 6],
        [9, 2, 4]]))

In [119]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[ 1.13376944, -1.09989127, -0.17242821, -0.87785842,  0.04221375],
       [ 0.58281521, -1.10061918,  1.14472371,  0.90159072,  0.50249434],
       [ 0.90085595, -0.68372786, -0.12289023, -0.93576943, -0.26788808]])

In [110]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.